language: objective-c
os: osx
osx_image: xcode9.2

env:
  matrix:
    - FORMULA_VERSION= FORMULA_OPTS=
    - FORMULA_VERSION=--HEAD FORMULA_OPTS=
    - FORMULA_VERSION=--HEAD FORMULA_OPTS=--with-java-bindings

before_install:
  - brew update
  - brew upgrade python
  - brew upgrade automake
  # Make sure that the formula works without wget installed
  - brew remove wget

install:
  - mkdir -p $(brew --repo)/Library/Taps/cvc4
  - ln -s $PWD $(brew --repo)/Library/Taps/cvc4/homebrew-cvc4
  - brew tap --repair

script:
  - brew audit cvc4/cvc4/cvc4
  - [ -n "$FORMULA_VERSION" ] && brew install cvc4/cvc4/cryptominisat
  - brew install cvc4/cvc4/cvc4 ${FORMULA_VERSION} ${FORMULA_OPTS} --verbose
  - brew test cvc4
  - cvc4 --version

notifications:
  email:
    on_success: never
    on_failure: always
