language: cpp
os: osx
env:
  matrix:
    - FORMULA_VERSION=
before_install:
  - brew update
  - brew --env
  - brew config
install:
  - mkdir -p $(brew --repo)/Library/Taps/CVC4
  - ln -s $TRAVIS_BUILD_DIR $(brew --repo)/Library/Taps/CVC4/homebrew-cvc4
  - brew tap --repair
script:
  - brew install cvc4 $FORMULA_VERSION --verbose
  - brew audit cvc4 --strict
  - brew test cvc4
  - cvc4 --version
