name: CI
on:
  push:
  pull_request:
  schedule:
    # Run every day at 1am
    - cron: '0 1 * * *'

jobs:
  build:
    strategy:
      matrix:
        name: [latest-release, head]

        include:
          - name: latest-release

          - name: head
            config: --HEAD

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        brew update 
        # Make sure that we do not require wget to be installed
        brew remove wget
        mkdir -p "$(brew --repo)/Library/Taps/cvc4"
        ln -s "${{ github.workspace }}" "$(brew --repo)/Library/Taps/cvc4/homebrew-cvc4"
    - name: Audit
      run: brew audit --formula "${{ github.workspace }}/Formula/cvc4.rb"
    - name: Install
      run: brew install cvc4/cvc4/cvc4 --verbose ${{ matrix.config }}
    - name: Test
      run: |
        brew test cvc4
        cvc4 --version
