name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Setup
      run: |
        brew update 
        # Make sure that we do not require wget to be installed
        brew remove wget
        mkdir -p $(brew --repo)/Library/Taps/cvc4
        ln -s $PWD $(brew --repo)/Library/Taps/cvc4/homebrew-cvc4
        echo $(brew --repo)
        ls -al $(brew --repo)/Library/Taps
        ls -al $(brew --repo)/Library/Taps/cvc4
        ls -al $(brew --repo)/Library/Taps/cvc4/homebrew-cvc4/
        # - name: Audit
        #   run: brew audit cvc4/cvc4/cvc4
    - name: Install
      run: brew install cvc4/cvc4/cvc4 --verbose
    - name: Test
      run: |
        brew test cvc4
        cvc4 --version
