name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        name: [latest-release, head, head-java]

        include:
          - name: latest-release
            
          - name: head
            config: --HEAD
            
          - name: head-java
            config: --HEAD --with-java-bindings
            
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Audit formula
      run: brew audit ${{ github.workspace }}/Formula/cvc4.rb

    - name: Install formula
      run: brew install -v ${{ github.workspace }}/Formula/cvc4.rb ${{ matrix.config }}

    - name: Test installation
      run: brew test cvc4
      
    - name: Show config
      run: cvc4 --show-config
